import journey
import time
def chapter4():
    print("Dave: I thought I told you to stay in the village")
    time.sleep(1)
    print("You tell your brother that you got tired of waiting and got worried")
    time.sleep(1)
    print("Dave: *sigh* Let's go back to the village, there is something I must tell everyone")
    time.sleep(1)
    print("*a little later*")
    time.sleep(3)
    print("Dave: Everyone listen! On my road to find you all I discovered something terrifying")
    time.sleep(3)
    print("*the crowd murmurs*")
    time.sleep(3)
    print("Dave: The monster I beat is just the baby, The mother will be coming here to get revenge for her son")
    time.sleep(2)
    print("*the crowd panics*")
    time.sleep(1)
    print("Dave: Relax! I have a plan! the monster only knows of this village and the nearby village hasn't had any attacks, They will let us move you all there. I will face the mother myself")
    time.sleep(1)
    print("*the crowd goes silent*")
    time.sleep(1)
    print("Dave: little ones, older ones, You must leave now...you too")
    time.sleep(3)
    print("*Dave points at you*")
    time.sleep(3)
    print("Dave: I'll wait on the mother, I'll be fine")
    time.sleep(1)
    print("You leave with the rest of the villagers")
    journey.journey()