import helpkids
import time
def chapter2():
    print("*after 5 minutes of searching*")
    time.sleep(5)
    print("Dave: hmmm...It's quiet out here. I don't like this one bit, stay close.")
    time.sleep(2)
    print("*you and Dave hear a child cry for help and run towards them*")
    time.sleep(3)
    print("Dave: what happened? are you okay?")
    time.sleep(2)
    print("Child: The monster took my parents and doll")
    time.sleep(2)
    print("Dave: Monster? where? how big?")
    time.sleep(2)
    print("Child: real big and scary! He went that way!")
    time.sleep(2)
    print("Dave: Ok, you stay here. I'll go handle the monster myself")
    time.sleep(2)
    print("*Dave runs out the town*")
    time.sleep(2)
    print("Child: There are more kids around here, you should help them")
    helpkids.helpkids()
    print("The children rejoice and you gather them all in your house")
    time.sleep(2)
    print("*Hours pass and your brother hasn't returned*")